services:
  - type: web
    plan: free
    name: conexao-digital-backend
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn conexao_digital.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: "django"
      - key: CORS_ALLOWED_ORIGINS
        value: http://localhost:5173,http://127.0.0.1:5173
      
