# Generated by Django 5.1.1 on 2024-09-19 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienciaProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('ano_inicio', models.IntegerField()),
                ('ano_fim', models.IntegerField(blank=True)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'experiência profissional',
                'verbose_name_plural': 'experiências profissionais',
                'ordering': ('cargo',),
            },
        ),
        migrations.CreateModel(
            name='FormacaoAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=100)),
                ('instituicao', models.CharField(max_length=100)),
                ('ano_inicio', models.IntegerField()),
                ('ano_conclusao', models.IntegerField()),
                ('semestre', models.IntegerField()),
            ],
            options={
                'verbose_name': 'formação acadêmica',
                'verbose_name_plural': 'formações acadêmicas',
                'ordering': ('curso',),
            },
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nivel', models.IntegerField(choices=[(1, 'Iniciante'), (2, 'Intermediário'), (3, 'Avançado')])),
            ],
            options={
                'verbose_name': 'habilidade',
                'verbose_name_plural': 'habilidades',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Interesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'interesse',
                'verbose_name_plural': 'interesses',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'projeto',
                'verbose_name_plural': 'projetos',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('ano_nascimento', models.IntegerField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default=None, max_length=1)),
                ('telefone', models.CharField(max_length=15)),
                ('deficiencia', models.BooleanField(blank=True, default=False)),
                ('resumo', models.TextField(blank=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('experiencias_profissionais', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='conexao_digital_api.experienciaprofissional')),
                ('formacoes_academicas', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='conexao_digital_api.formacaoacademica')),
                ('habilidades', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='conexao_digital_api.habilidade')),
                ('interesses', models.ManyToManyField(blank=True, related_name='usuarios', to='conexao_digital_api.interesse')),
                ('projetos', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='conexao_digital_api.projeto')),
            ],
            options={
                'verbose_name': 'pessoa',
                'verbose_name_plural': 'pessoas',
                'ordering': ('nome',),
            },
        ),
    ]
