# Generated by Django 5.1.1 on 2024-09-19 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexao_digital_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
    ]
