# Generated by Django 5.1.1 on 2024-09-19 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexao_digital_api', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='deficiencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='experiencias_profissionais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='conexao_digital_api.experienciaprofissional'),
        ),
        migrations.AlterField(
            model_name='user',
            name='formacoes_academicas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='conexao_digital_api.formacaoacademica'),
        ),
        migrations.AlterField(
            model_name='user',
            name='habilidades',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='conexao_digital_api.habilidade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='interesses',
            field=models.ManyToManyField(blank=True, null=True, related_name='usuarios', to='conexao_digital_api.interesse'),
        ),
        migrations.AlterField(
            model_name='user',
            name='projetos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='conexao_digital_api.projeto'),
        ),
        migrations.AlterField(
            model_name='user',
            name='resumo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
