# Generated by Django 5.1.1 on 2024-09-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexao_digital_api', '0003_alter_user_avatar_alter_user_deficiencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interesses',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='conexao_digital_api.interesse'),
        ),
    ]
