# Generated by Django 5.1.1 on 2024-09-19 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexao_digital_api', '0004_alter_user_interesses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='experiencias_profissionais',
        ),
        migrations.RemoveField(
            model_name='user',
            name='formacoes_academicas',
        ),
        migrations.RemoveField(
            model_name='user',
            name='habilidades',
        ),
        migrations.RemoveField(
            model_name='user',
            name='interesses',
        ),
        migrations.RemoveField(
            model_name='user',
            name='projetos',
        ),
        migrations.AddField(
            model_name='experienciaprofissional',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiencias_profissionais', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formacaoacademica',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formacoes_academicas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interesse',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='interesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projeto',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to=settings.AUTH_USER_MODEL),
        ),
    ]
