# Generated by Django 5.1.1 on 2024-09-22 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conexao_digital_api', '0005_remove_user_experiencias_profissionais_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ano_nascimento',
            new_name='idade',
        ),
    ]
